### PR TITLE
Added AsyncView decorator for rendering async body

### PR DESCRIPTION
**Pull request by hironichu**
I've noticed That you can't use the View() decorator on Promises because the body isn't awaited in the non async View method, 

Was this intentional design ? 

I need to see if i can add some tests but this works for now, i will continue working on it as i continue the integration in my project.

### CODE REVIEW

**Comment by herudi** [comment]
hi @hironichu, thanks for good investigation. It should be designed to support async/sync. maybe I forgot to add async. however, can you just put it in the View decorator? without creating another decorator. 

best regards.

**Comment by herudi** [comment]
however @hironichu to support async methods, this should use await. right?
https://github.com/nhttp/nhttp/blob/83f1b922cbe91b27952b86091cea05e65aa52293/lib/controller.ts#L101

**Comment by hironichu** [comment]
Yeah my bad i was working on it :D

**Comment by herudi** [comment]
thanks. this is done 👍

**Pull request merged**
